### ISSUE TITLE
steam联机版进入服务器报错

### ISSUE THREAD

**Issue by adaxe** [paintdream/DontStarveLuaJIT#10]
log如下：
https://pastebin.com/rha4SnU3

**Comment by paintdream** [comment]
看来与这个758532836的mod有关，放假时我研究下

**Comment by paintdream** [comment]
再试试最新版本的看看？

**Comment by adaxe** [comment]
> 再试试最新版本的看看？

可以正常加载了，问题应该是解决了。

**Comment by paintdream** [comment]
> > 再试试最新版本的看看？
> 
> 可以正常加载了，问题应该是解决了。

OK
