### ISSUE TITLE
debug.getinfo(stacklevel, "S").what returns "Lua" instead of "main" when kleloadlua is used to load files.

### ISSUE THREAD

**Issue by Zarklord** [paintdream/DontStarveLuaJIT#15]
This poses a big problem because of DST's strict.lua which allows setting values to work, but only if the code block is considered to be a "main" chunk, and not just a lua function(in which case the game would crash), this is a very important and key functionality to DST and must be preserved across to LuaJIT.

**Comment by paintdream** [comment]
The behavior of debug library of LuaJIT varies from original ones. For example, LuaJIT does not count tailcalls on function stack level. 

I've bypassed the compatibility problems between LuaJIT & GemCore by replacing tailcalls with normal function call, by matching code text. It's not the best choice but I have no better idea. see: https://github.com/paintdream/DontStarveLuaJIT/blob/master/src/luajit/src/lib_package.c#L476

Have you released a new verison of GemCore and change the code that calls debug.getinfo()? If so, it would be better if you could remove tail calls on debug.getinfo.... THEN I could remove these unly code....

INSTRUCTIONS: Just as described here: https://github.com/paintdream/DontStarveLuaJIT#to-mod-developers%E5%AF%B9%E4%BA%8Emod%E5%BC%80%E5%8F%91%E8%80%85

Replace:
```
function a(option)
	return debug.getinfo(1, "option")
end
```

with: 

```
function a(option)
	return debug.getinfo(1, "option"), nil
end
```

**Comment by Zarklord** [comment]
Except thats the weird part, the crash occurs when enabling Gem Core, and I'm not doing the debug call, the game is.
take this crash log: https://pastebin.com/rkLRcJzK the game crashes when GemCore sets a function to `GetModModConfigData` in the global namespace, the stacktrace even shows that the chunk is considered a "Lua" chunk(line 274 of that crash log), when I was testing on my machine(which doesn't have this installed), I could consistently get debug.getinfo to show the chunk as a "main" chunk, this is not my call to debug.getinfo, and therefore I can't fix it.

**Comment by paintdream** [comment]
I've upgraded GemCore to latest and **it runs well**. Have you applied the latest DontStarveLuaJIT patch?

-----------------
OK, let me tell you what happened serveral months ago:

In strict.lua, klei calls debug.getinfo to test if you are in "main":

```
mt.__newindex = function (t, n, v)
  if __STRICT and not mt.__declared[n] then
    local w = debug.getinfo(2, "S").what
    if w ~= "main" and w ~= "C" then
      error("assign to undeclared variable '"..n.."'", 2)
    end
    mt.__declared[n] = true
  end
  rawset(t, n, v)
end
```

It works fine. But GemCore hooked the debug.getinfo() in fnhider.lua:
```

local _debug_getinfo = debug.getinfo
function debug.getinfo(...)
    local args = {...}
    local fnidx = (#args == 3 or (#args == 2 and type(args[2]) ~= "string")) and 2 or 1
    local fn = args[fnidx]
    if type(fn) ~= "function" then
        local stack_count, current, traversed = fn + 1, 2, 1
        if fn > 0 then
            --jump over this function replacement.
            fn = fn + 1
        end
        while traversed < stack_count do
            if hiddenfns[(_debug_getinfo(current, "f") or {}).func] then
                fn = fn + 1
            else
                traversed = traversed + 1
            end
            current = current + 1
        end
        args[fnidx] = fn
    else
        args[fnidx] = hiddenfns[fn] or fn
    end
    return _debug_getinfo(unpack(args)) --<<<<<<<<<<<<<<<<< Look at here!
end
```

You call original debug.getinfo in tail call, which behaviour divers from lua and luajit: **Lua count the tail call as a layer of stack while LuaJIT not**. So after applying fnhider.lua, the layer is not correct in LuaJIT.

So I fixed this problem by hooking kleiloadlua to replace your code with:

`
    return _debug_getinfo(unpack(args)), nil -- Add nil HERE!
`

And it works fine now. 


**So if you can do the same change as I described above, THEN I could remove the hook to kleiloadlua and everything works fine.
So it look weird that it still crash in your computer. Maybe you are not applied the latest patch? I guess.**


**Here is my case: (Enabling GemCore with Global Pause, as well as DontStarveLuaJIT, and all things are good)**

![image](https://user-images.githubusercontent.com/7030141/87876252-64a0d600-ca09-11ea-9a5a-2983f43769c7.png)

![image](https://user-images.githubusercontent.com/7030141/87876285-d11bd500-ca09-11ea-9437-4df232cfd40d.png)

**Comment by Zarklord** [comment]
Hmm, it must be that the person who reported the bug must have been running an outdated version of LuaJIT, I'll fix the tailcalls in my next release so you can remove those hacks.

**Comment by paintdream** [comment]
> Hmm, it must be that the person who reported the bug must have been running an outdated version of LuaJIT, I'll fix the tailcalls in my next release so you can remove those hacks.

Thanks a lot~

The GemCore is powerful. Thanks the contribution to Don't Starve 's world!
