### ISSUE TITLE
有linux版么

### ISSUE THREAD

**Issue by duguying** [paintdream/DontStarveLuaJIT#2]
有linux 版么

**Comment by Iamanorange** [comment]
没有。。

**Comment by paintdream** [comment]
目前木有== Linux版相当于要重写一遍，玩的人也不多……

**Comment by duguying** [comment]
搭独立服务器linux多啊

**Comment by jupitersh** [comment]
嗯 Linux服务器极度需要

**Comment by paintdream** [comment]
现在Linux版本的Dedicated Server已经在支持了，由于linux的特殊性，可能需要自行编译。详见README.md

**Comment by paintdream** [comment]
> 嗯 Linux服务器极度需要

目前我在Debian 8.5上做的测试，其他的版本可能需要自行编译。

**Comment by paintdream** [comment]
Linux版本的反馈另开issue吧=这个我就关了~
