### ISSUE TITLE
我遇到了一些麻烦

### ISSUE THREAD

**Issue by Ember-github** [paintdream/DontStarveLuaJIT#3]
你好，饥荒服务器运行一段时间后，无缘无故闪退，多次。用调试器看到最后发生了这个7异常；还有一个问题是这个patch跟GemCore这个mod不兼容，报错跟strict.lua有关。

使用x32dbg看log，得到如下信息
-------------------------------------------------------------------------------------------
调试字符串： "[01:01:34]: Serializing world: session/09912D5C83CFD5D6/0000000131"
调试字符串： "[01:01:34]: Truncating to snapshot #131..."
调试字符串： "[01:01:34]:  - session/09912D5C83CFD5D6/0000000123"
调试字符串： "[01:01:34]:    1 file(s) removed"
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000005 (EXCEPTION_ACCESS_VIOLATION)
          ExceptionFlags: 00000000
        ExceptionAddress: 01067D20 lua51.01067D20
        NumberParameters: 2
ExceptionInformation[00]: 00000000 Read
ExceptionInformation[01]: 00000085 Inaccessible Address
第一次异常于 01067D20 (C0000005, EXCEPTION_ACCESS_VIOLATION)！

**Comment by paintdream** [comment]
服务器是哪个版本的饥荒？是否有开洞穴？客户端是无patch/部分开启patch还是全部开启patch?

GeoCore的问题我抽空看下~

**Comment by Ember-github** [comment]
我的服务器系统是`Windows Server 2019 Datacenter` `1809` `64位`，版本号`17763.379`  。饥荒服务端是`Steam`版的`Don't Starve Together Dedicated Server`，版本号`393281`。多层世界有洞穴，客户端无此patch，虽然我并不能排除是mod问题，但当我取消使用此补丁时，已经可以长时间稳定运行。我使用的MOD如下：
```lua
--# 二本垃圾桶
ServerModSetup("1214740157")
--# 中文语言包
ServerModSetup("1301033176")
--# 五格装备栏
ServerModSetup("1405120786")
--# 定位
ServerModSetup("378160973")
--#Show me
ServerModSetup("666155465")
--# 复活
ServerModSetup("462434129")
--# 防熊
ServerModSetup("1714227968")
--# 蘑菇房
--ServerModSetup("1951468597")
--# 浆果丛转换
--ServerModSetup("1164008740")
--# 灯笼增强
ServerModSetup("1304220128")
--# No Vote
ServerModSetup("709986084")
--# 无草蜥蜴
ServerModSetup("797304209")
--# 新多层选择器
ServerModSetup("1754389029")
--# 木糖田园
ServerModSetup("1989965008")
--# 你可以刨土种地
ServerModSetup("1985042477")
--# Iron fence
ServerModSetup("1463492447")
--# 额外物品包
ServerModSetup("1085586145")
--# 能力勋章 Functional Medal
ServerModSetup("1909182187")
--# 全面加强
ServerModSetup("1557167881")
--# UI木牌传送
ServerModSetup("1530801499")
--# Berg Cub
ServerModSetup("1577400707")
--# <default>'s item pack (DST)
ServerModSetup("436897772")
--# 花样风滚草 Interesting Tumbleweed
ServerModSetup("1944492666")
```

**Comment by paintdream** [comment]
没有找到叫gem core的mod，能提供一下创意工坊的链接吗？

服务器的问题有可能是内存不足引起的，LuaJit比lua需要更多的内存。windows上32位程序默认只能使用2g用户地址空间，如果你发现服务器运行时的进程内存达1.5g甚至更多，则有可能造成内存不足。服务器版本的windows可以将这个限制放宽至3gb，https://docs.microsoft.com/zh-cn/previous-versions/exchange-server/exchange-server-2000/bb124810(v=exchg.65)

如果可能的话可否提供存档至paintdream@paintdream.com

**Comment by Ember-github** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1378549454
感谢

**Comment by paintdream** [comment]
Gem Core的问题我把strict.lua直接废掉了。可下载最新版本试试。

LuaJIT和Lua在栈上的处理可能不一样，没细看。debug.getinfo(2, "S")这种做法过于hack，干脆直接做掉，访问全局变量还能快些。
