### ISSUE TITLE
和神话书说mod有冲突。

### ISSUE THREAD

**Issue by adaxe** [paintdream/DontStarveLuaJIT#4]
和神话书说mod（workshop-1697986974）冲突，导致mod崩溃，自动禁用。去除流畅化补丁后可以正常加载。
错误日志如下：
https://pastebin.com/NqJBw5ec

**Comment by paintdream** [comment]
应该和那个神奇的.mp4有关，等有windows的时候我看下。

**Comment by paintdream** [comment]
已经修掉了，请下载最新版本。
