### ISSUE TITLE
Linux服务器版装上周期性卡一下

### ISSUE THREAD

**Issue by imcloudf** [paintdream/DontStarveLuaJIT#8]
频率大概是十几秒一次, 关掉延迟补偿很容易发现
一个服装了
Show Bundle (2.5)
Smart Minisign (1.1.3)
Auto Stack and Pick Up (0.1.5)
另一个服装了
H1Z1饥荒大逃杀 (1.0.3)
在装上补丁之前没出现过这个情况
都是Ubuntu 18.04 系统, 用的 lib32readline-dev 这个包

**Comment by paintdream** [comment]
机器的配置大约是什么样的，CPU使用率是否也有同样的同期性变化？

**Comment by paintdream** [comment]
用最新的试试看是否有所缓解？

**Comment by imcloudf** [comment]
> 用最新的试试看是否有所缓解？

一个人测试了一下, 似乎没有出现了

**Comment by imcloudf** [comment]
> 用最新的试试看是否有所缓解？

我朋友说了, 还是会卡, 占用正常, 服务器是 2c4g5m的

**Comment by paintdream** [comment]
> > 用最新的试试看是否有所缓解？
> 
> 我朋友说了, 还是会卡, 占用正常, 服务器是 2c4g5m的

多久卡一次？对比原版呢

**Comment by imcloudf** [comment]
> > > 用最新的试试看是否有所缓解？
> > 
> > 
> > 我朋友说了, 还是会卡, 占用正常, 服务器是 2c4g5m的
> 
> 多久卡一次？对比原版呢

我朋友说是一两分钟一次 = =

**Comment by paintdream** [comment]
@imcloudf 

试试这个版本：

https://github.com/paintdream/DontStarveLuaJIT/releases/tag/2020.6.19

**Comment by imcloudf** [comment]
> @imcloudf
> 
> 试试这个版本：
> 
> https://github.com/paintdream/DontStarveLuaJIT/releases/tag/2020.6.19

0.0 好久没玩游戏了, 服务器也没在搞了

**Comment by zhychhit** [comment]
@paintdream 还是会有，频率大约两分钟一次，卡顿时 CPU 有一个很短暂的峰值，类似于保存时的卡顿
也是 Ubuntu 18.04，lib32readline-dev 这个包

**Comment by zhychhit** [comment]
换成Ubuntu 14.04，lib32readline6，问题依旧，但卡顿周期稍有增加，约两分半钟卡一次
