### ISSUE TITLE
Linux dst 客户端使用失败

### ISSUE THREAD

**Issue by XuHenghenglumia** [paintdream/DontStarveLuaJIT#9]
发行版archlinux，dontstarve_dedicated_server_nullrenderer能跑，但是dontstarve_steam（客户端）运行报错，报错形如
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`/home/xuheng/.local/share/Steam/ubuntu12_32/steam steam://run/322330`
`ERROR: ld.so: object 'libpreload.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`
`[00:00:00]: Steam doesn't seem to be running. Trying to restart the game via Steam.`
`[00:00:00]: Error, Steam failed to initialize, result=1...`
`[00:00:00]: The application will now exit`
`Updates 0Seconds elapsed: 0.27328 fps:0`
`[00:00:00]: Shutting down`
BTW,我玩的一个档使用了luajit patch，我进入他的档，跳世界时会因为一个中文字体mod导致客户端闪退，而linux版饥荒不用第三方中文字体mod，中文有一半是乱码，就很难受。尝试了多个中文字体mod，全军覆没。

**Comment by paintdream** [comment]
Linux版本目前仅支持Dedicated Server。Linux客户端由于会请求steam启动自己，因而libpreload.so是加载不了的，除非有办法能改掉steam启动游戏时的环境变量。

中文字体MOD是哪一个？有创意工坊的id吗我看下。

**Comment by XuHenghenglumia** [comment]
> Linux版本#目前仅支持Dedicated Server。Linux客户端由于会请求steam启动自己，因而libpreload.so是加载不了的，除非有办法能改掉steam启动游戏时的环境变量。
> 
> 中文字体MOD是哪一个？有创意工坊的id吗我看下。

1418746242 [汉化增强 Chinese++（含中文高清字体）](https://steamcommunity.com/sharedfiles/filedetails/?id=1418746242&searchtext=chinese)
貌似不是100%重现，但是概率很大

**Comment by paintdream** [comment]
> > Linux版本#目前仅支持Dedicated Server。Linux客户端由于会请求steam启动自己，因而libpreload.so是加载不了的，除非有办法能改掉steam启动游戏时的环境变量。
> > 中文字体MOD是哪一个？有创意工坊的id吗我看下。
> 
> 1418746242 [汉化增强 Chinese++（含中文高清字体）](https://steamcommunity.com/sharedfiles/filedetails/?id=1418746242&searchtext=chinese)
> 貌似不是100%重现，但是概率很大

收到，我抽空看看=

**Comment by paintdream** [comment]
> > Linux版本#目前仅支持Dedicated Server。Linux客户端由于会请求steam启动自己，因而libpreload.so是加载不了的，除非有办法能改掉steam启动游戏时的环境变量。
> > 中文字体MOD是哪一个？有创意工坊的id吗我看下。
> 
> 1418746242 [汉化增强 Chinese++（含中文高清字体）](https://steamcommunity.com/sharedfiles/filedetails/?id=1418746242&searchtext=chinese)
> 貌似不是100%重现，但是概率很大

试了几次似乎都没发现问题……

![Screenshot from 2020-04-17 23-05-06](https://user-images.githubusercontent.com/7030141/79583795-19bcad00-8100-11ea-9f37-9ba55a17bdcf.png)
